-- Generated by the database client.
CREATE TABLE a1_provinsi(
    id character(2) NOT NULL,
    nama varchar(255) NOT NULL,
    PRIMARY KEY(id)
);

-- Generated by the database client.
CREATE TABLE a2_kota(
    id character(4) NOT NULL,
    provinsi_id character(2) NOT NULL,
    nama varchar(255) NOT NULL,
    PRIMARY KEY(id),
    CONSTRAINT wil_regional_provinsi_id_fkey FOREIGN key(provinsi_id) REFERENCES a1_provinsi(id)
);
CREATE INDEX regional_provinsi_id_index ON public.a2_kota USING btree (provinsi_id);

-- Generated by the database client.
CREATE TABLE a3_kecamatan(
    id character(7) NOT NULL,
    regional_id character(4) NOT NULL,
    nama varchar(255) NOT NULL,
    PRIMARY KEY(id),
    CONSTRAINT wil_kecamatan_regional_id_fkey FOREIGN key(regional_id) REFERENCES a2_kota(id)
);
CREATE INDEX kecamatan_id_index ON public.a3_kecamatan USING btree (regional_id);

-- Generated by the database client.
CREATE TABLE a4_desa(
    id character(20) NOT NULL,
    kecamatan_id character(20),
    nama varchar(255),
    PRIMARY KEY(id),
    CONSTRAINT wil_desa_kecamatan_id_fkey FOREIGN key(kecamatan_id) REFERENCES a3_kecamatan(id)
);
CREATE INDEX desa_kecamatan_id_index ON public.a4_desa USING btree (kecamatan_id);

-- Generated by the database client.
CREATE TABLE alamat(
    id SERIAL NOT NULL,
    userid integer,
    provinsi varchar(255),
    kota varchar(255),
    kecamatan varchar(255),
    desa varchar(255),
    alamat varchar(255),
    kode_pos numeric,
    jarak numeric,
    transportasi varchar(255),
    createdat timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);

-- Generated by the database client.
CREATE TABLE asal_sekolah(
    id SERIAL NOT NULL,
    userid integer,
    npsn text,
    nama varchar(255),
    provinsi varchar(255),
    kota varchar(255),
    kecamatan varchar(255),
    desa varchar(255),
    createdat timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


-- Generated by the database client.
CREATE TABLE berkas(
    id SERIAL NOT NULL,
    user_id integer,
    file_name varchar(255) NOT NULL,
    file_link text NOT NULL,
    PRIMARY KEY(id)
);

-- Generated by the database client.
CREATE TABLE info(
    id SERIAL NOT NULL,
    judul varchar(255),
    teks text NOT NULL,
    kategori varchar(100) NOT NULL,
    createdat timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(id)
);

-- Generated by the database client.
CREATE TABLE jadwal(
    id SERIAL NOT NULL,
    waktu timestamp with time zone,
    jenis varchar(255),
    kegiatan varchar(255),
    mode varchar(255),
    kuota integer,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(id)
);

-- Generated by the database client.
CREATE TABLE jadwal_user(
    id SERIAL NOT NULL,
    user_id integer,
    jadwal_id integer,
    waktu timestamp with time zone,
    jenis varchar(255),
    kegiatan varchar(255),
    mode varchar(255),
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(id)
);

-- Generated by the database client.
CREATE TABLE jawaban(
    id SERIAL NOT NULL,
    user_id integer,
    soal_id integer,
    jawaban text,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(id)
);

-- Generated by the database client.
CREATE TABLE jenjang(
    id SERIAL NOT NULL,
    nama varchar(100) NOT NULL,
    createdat timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(id)
);

-- Generated by the database client.
CREATE TABLE keluarga(
    id SERIAL NOT NULL,
    user_id integer,
    nama varchar(255) NOT NULL,
    tanggal_lahir date NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(id)
);

-- Generated by the database client.
CREATE TABLE kuis(
    id SERIAL NOT NULL,
    jenis varchar(255),
    soal text,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    pengisi varchar(255),
    PRIMARY KEY(id)
);

-- Generated by the database client.
CREATE TABLE pembayaran(
    id SERIAL NOT NULL,
    nama text NOT NULL,
    user_id integer NOT NULL,
    media varchar(225) NOT NULL,
    nominal bigint NOT NULL,
    berkas text NOT NULL,
    ket boolean DEFAULT false,
    tgl_bayar timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(id)
);

-- Generated by the database client.
CREATE TABLE pendaftar(
    id SERIAL NOT NULL,
    userid integer,
    kode_pendaftaran varchar(255),
    status_pendaftaran varchar(255),
    jenjang_id integer,
    tapel_id integer,
    sekolah_id integer,
    nisn bigint,
    no_kk bigint,
    nik bigint,
    no_akta text,
    nama varchar(255),
    tempat_lahir varchar(255),
    tanggal_lahir date,
    kelamin varchar(20),
    agama varchar(100),
    anak_ke integer,
    jml_saudara integer,
    tinggi numeric,
    berat numeric,
    kepala numeric,
    ayah_nik bigint,
    ayah_nama varchar(255),
    ayah_tempat_lahir varchar(255),
    ayah_tanggal_lahir date,
    ayah_pendidikan varchar(255),
    ayah_pekerjaan varchar(255),
    ayah_no_tlp bigint,
    ibu_nik bigint,
    ibu_nama varchar(255),
    ibu_tempat_lahir varchar(255),
    ibu_tanggal_lahir date,
    ibu_pendidikan varchar(255),
    ibu_pekerjaan varchar(255),
    ibu_no_tlp bigint,
    createdat timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pendaftar_jenjang_id_fkey FOREIGN key(jenjang_id) REFERENCES jenjang(id),
    CONSTRAINT pendaftar_sekolah_id_fkey FOREIGN key(sekolah_id) REFERENCES sekolah(id),
    CONSTRAINT pendaftar_tapel_id_fkey FOREIGN key(tapel_id) REFERENCES tapel(id)
);

-- Generated by the database client.
CREATE TABLE sekolah(
    id SERIAL NOT NULL,
    nama varchar(100) NOT NULL,
    createdat timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(id)
);

-- Generated by the database client.
CREATE TABLE tapel(
    id SERIAL NOT NULL,
    tapel varchar(100) NOT NULL,
    createdat timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(id)
);

-- Generated by the database client.
CREATE TABLE user_info(
    id SERIAL NOT NULL,
    nama varchar(100) NOT NULL,
    email varchar(100) NOT NULL,
    tlp varchar(255) NOT NULL,
    password varchar(100) NOT NULL,
    peran varchar(20) DEFAULT 'user'::character varying,
    createdat timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(id)
);

UPDATE berkas 
SET file_link = REPLACE(file_link, 'https://ppdb-api.nibs.sch.id', '')
WHERE file_link LIKE '%https://ppdb-api.nibs.sch.id%';

UPDATE pembayaran 
SET berkas = REPLACE(berkas, 'https://ppdb-api.nibs.sch.id', '')
WHERE berkas LIKE '%https://ppdb-api.nibs.sch.id%';